image: "registry.gitlab.com/qvex/vex-rt-ci-container:latest"

stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  CARGO_TERM_COLOR: always

before_script:
  - rustc --version && cargo --version  # Print version info for debugging

build:
  stage: build
  variables:
    RUSTFLAGS: -D warnings
    RUSTDOCFLAGS: -D warnings --cfg docsrs
  script:
    - cargo fmt -- --check
    - cargo build --all-features
    - cargo build --examples --all-features
    - cargo clippy --all-features -- -D warnings
    - cargo clippy --examples --all-features -- -D warnings
    - cargo doc --all-features
  cache:
    paths:
      - .cargo
      - target