image: "registry.gitlab.com/qvex/vex-rt-ci-container:latest"

stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

before_script:
  - rustc --version && cargo --version  # Print version info for debugging

build:
  stage: build
  script:
    - cargo build
    - cargo build --examples
  cache:
    paths:
      - .cargo
      - target

format:
  stage: build
  script: cargo fmt -- --check
