[package]
name = "vex-rt"
version = "0.1.0"
authors = ["Timothy Morland <me@timothy-morland.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2", default-features = false }

[dev-dependencies]
libc-print = "0.1.14"
