name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - run: sudo apt-get install gcc-arm-none-eabi
    # - run: rustup component add rust-src
    - run: cargo check --verbose
    - run: cargo check --examples --verbose
    # - run: cargo test --verbose
